name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install, build, and test
        run: |
          yarn
          #yarn lint
          yarn build
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check git clean
        if: github.ref == 'refs/heads/master' || (github.event_name == 'pull_request' && github.base_ref == 'refs/heads/master')
        run: './.github/scripts/check-clean.sh'
